apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gnrvdel85-nodejs 
  janus-idp.io/tekton: gnrvdel85-nodejs
  backstage.io/kubernetes-id: gnrvdel85-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gnrvdel85-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml